
spring:
  datasource:
    url: jdbc:mysql://cs8803db.czdpqaof1gql.us-east-1.rds.amazonaws.com:3306/first_assignment
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver