spring:
  datasource:
    url: jdbc:mysql://cs8803db.czdpqaof1gql.us-east-1.rds.amazonaws.com:3306/first_assignment
#    url: jdbc:${DB_URL}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
    username: admin
    password: weakpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 5000